### ISSUE TITLE
getPskEntry unit test bug

### ISSUE THREAD

**Issue by adithya-22** [Seagate/TCGstorageAPI#13]
**Describe the bug**
The latest changes to the tcgapi caused a couple of test cases, particularly related to that of the getPskEntry function to fail. It raises an exception when handling the conversion of integers from bytes to hexadecimal. 

**To Reproduce**
1. Build steps 
     python3 setup.py opensea
     python3 setup.py build
2. Python script :test_tcgapi.py
     Command: python3 test_tcgapi.py
3. Type of drive interface that's being used (SAS/SATA).
4. Product type: Seagate SED

**Expected behavior**
The unit tests should not raise an exception and handle the base conversion appropriately.

**Desktop**
 - OS: CentOS 7
 - Python version: 3.6

**Comment by Keerthana-Bidarakoppa** [comment]
This issue has been fixed in the recent commit. I am closing this issue.
