### ISSUE TITLE
How can I contribute to TCGstorageAPI project?

### ISSUE THREAD

**Issue by simonpha** [Seagate/TCGstorageAPI#14]
Hi, I found the TCGstorageAPI project interesting and want to contribute to the project. Are there any guidelines that contributors need to follow to add new features or improvement to the project and create a Pull request for the same?

**Comment by gpepus** [comment]
> Hi, I found the TCGstorageAPI project interesting and want to contribute to the project. Are there any guidelines that contributors need to follow to add new features or improvement to the project and create a Pull request for the same?

Hi Simon ... There are potential things that you could do to help but I need to check with the Seagate Team to see what the priorities.  How are your Windows/Python dev skills?  There is a particular issue I have in mind which if someone would work it .. that would be great.  More in a little while.
Greg

**Comment by Keerthana-Bidarakoppa** [comment]
Hi Simon,

We are working on a Contributors file, defining the guidelines of how you can contribute to the project.
