### ISSUE TITLE
just a question on tcgapi_tests.py

### ISSUE THREAD

**Issue by gpepus** [Seagate/TCGstorageAPI#20]
my experience with pytest is such that if you don't name a pytest test file starting with test_ then you break the pytest automation or you have to adjust the pytest configuration file -- which is extra work.  WHY did Seagate change test_tcgapi.py to tcgapi_test.py?

**Comment by adithya-22** [comment]
Hi Greg, the file name can either start with "test_" or end with "_test" for the pytest framework to be able to discover the tests. [https://docs.pytest.org/en/reorganize-docs/new-docs/user/naming_conventions.html](url) 
The reason we changed the name is to increase readability by grouping the source code and the corresponding test file below it.
