### ISSUE TITLE
Question about drive manufacturers

### ISSUE THREAD

**Issue by wyllys66** [Seagate/TCGstorageAPI#21]
Not a bug, just a question...

Does this code work with any TCG Opal(V1|2) compliant device or only those made by Seagate?

**Comment by joebrand** [comment]
Wyllys,

Thanks for posing the question.

Our company has utilized and tested this code against several other drive
makers.  It has support for most, but not all of Opal V2.  I'm not aware of
any testing or support for Opal V1.
For Opal V2, the main functionality missing is code to manage the hidden
boot image for Opal V2 to decrypt at boot time.  If using an Opal V2 drive
as a data drive, the code will work for taking ownership and configuring
locking ranges.

Regards,

*[image: futuracyberemail]*

*Joseph Brand*

FUTURA Cyber Inc.

Chief Security Officer

**Comment by wyllys66** [comment]
Thanks!
